-- Дополнительные услуги для car-rent-miniapp
-- Запусти этот файл в Supabase → SQL Editor → New query → Run.

create extension if not exists pgcrypto;

create table if not exists extra_services (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  name text not null,
  description text,
  price numeric(10,2),
  price_type text not null default 'fixed', -- fixed, per_day_capped, request
  max_price numeric(10,2),
  extra_km int default 0,
  is_active boolean default true,
  sort_order int default 0,
  created_at timestamptz default now()
);

alter table extra_services add column if not exists description text;
alter table extra_services add column if not exists price numeric(10,2);
alter table extra_services add column if not exists price_type text not null default 'fixed';
alter table extra_services add column if not exists max_price numeric(10,2);
alter table extra_services add column if not exists extra_km int default 0;
alter table extra_services add column if not exists is_active boolean default true;
alter table extra_services add column if not exists sort_order int default 0;

create table if not exists booking_extra_services (
  id bigint generated by default as identity primary key,
  booking_id bigint references bookings(id) on delete cascade,
  service_id uuid references extra_services(id),
  service_code text not null,
  service_name text not null,
  price numeric(10,2),
  quantity int default 1,
  total numeric(10,2),
  created_at timestamptz default now()
);

insert into extra_services
(code, name, description, price, price_type, max_price, extra_km, is_active, sort_order)
values
('delivery_barcelona', '🚗 Доставка по Барселоне', 'Доставка автомобиля в пределах Барселоны', 30, 'fixed', null, 0, true, 1),
('delivery_airport', '✈️ Доставка в аэропорт BCN', 'Доставка автомобиля в аэропорт Barcelona-El Prat', 40, 'fixed', null, 0, true, 2),
('child_seat', '👶 Детское кресло', 'Детское кресло на весь срок аренды', 25, 'fixed', null, 0, true, 3),
('additional_driver', '👤 Дополнительный водитель', '10 €/день, максимум 50 €. Требуются документы и права второго водителя.', 10, 'per_day_capped', 50, 0, true, 4),
('night_service', '🌙 Ночная выдача/возврат', 'Выдача или возврат с 22:00 до 08:00', 30, 'fixed', null, 0, true, 5),
('return_other_place', '📍 Возврат в другом месте', 'В пределах Барселоны. За пределами города — по согласованию.', 50, 'fixed', null, 0, true, 6),
('extra_km_100', '🛣 Пакет +100 км', 'Дополнительные 100 км к лимиту пробега', 20, 'fixed', null, 100, true, 7),
('extra_km_300', '🛣 Пакет +300 км', 'Дополнительные 300 км к лимиту пробега', 50, 'fixed', null, 300, true, 8),
('no_wash_return', '🧽 Возврат без мойки', 'Можно вернуть автомобиль без обычной мойки. Сильное загрязнение оплачивается отдельно.', 20, 'fixed', null, 0, true, 9),
('cross_border', '🌍 Выезд за пределы Испании', 'Только по согласованию с менеджером', 0, 'request', null, 0, true, 10)
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  price_type = excluded.price_type,
  max_price = excluded.max_price,
  extra_km = excluded.extra_km,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;
