-- Дополнительные услуги для car-rent-miniapp
-- Запусти этот файл в Supabase → SQL Editor → New query → Run.

create extension if not exists pgcrypto;

create table if not exists extra_services (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  name text not null,
  description text,
  price numeric(10,2),
  price_type text not null default 'fixed', -- fixed, per_day_capped, request
  max_price numeric(10,2),
  extra_km int default 0,
  is_active boolean default true,
  sort_order int default 0,
  created_at timestamptz default now()
);

alter table extra_services add column if not exists description text;
alter table extra_services add column if not exists price numeric(10,2);
alter table extra_services add column if not exists price_type text not null default 'fixed';
alter table extra_services add column if not exists max_price numeric(10,2);
alter table extra_services add column if not exists extra_km int default 0;
alter table extra_services add column if not exists is_active boolean default true;
alter table extra_services add column if not exists sort_order int default 0;

create table if not exists booking_extra_services (
  id bigint generated by default as identity primary key,
  booking_id bigint references bookings(id) on delete cascade,
  service_id uuid references extra_services(id),
  service_code text not null,
  service_name text not null,
  price numeric(10,2),
  quantity int default 1,
  total numeric(10,2),
  created_at timestamptz default now()
);

insert into extra_services
(code, name, description, price, price_type, max_price, extra_km, is_active, sort_order)
values
('delivery_barcelona', '🚗 Доставка по Барселоне', 'Доставка автомобиля в пределах Барселоны', 30, 'fixed', null, 0, true, 1),
('delivery_airport', '✈️ Доставка в аэропорт BCN', 'Доставка автомобиля в аэропорт Barcelona-El Prat', 40, 'fixed', null, 0, true, 2),
('child_seat', '👶 Детское кресло', 'Детское кресло на весь срок аренды', 25, 'fixed', null, 0, true, 3),
('additional_driver', '👤 Дополнительный водитель', '10 €/день, максимум 50 €. Требуются документы и права второго водителя.', 10, 'per_day_capped', 50, 0, true, 4),
('night_service', '🌙 Ночная выдача/возврат', 'Выдача или возврат с 22:00 до 08:00', 30, 'fixed', null, 0, true, 5),
('return_other_place', '📍 Возврат в другом месте', 'В пределах Барселоны. За пределами города — по согласованию.', 50, 'fixed', null, 0, true, 6),
('extra_km_100', '🛣 Пакет +100 км', 'Дополнительные 100 км к лимиту пробега', 20, 'fixed', null, 100, true, 7),
('extra_km_300', '🛣 Пакет +300 км', 'Дополнительные 300 км к лимиту пробега', 50, 'fixed', null, 300, true, 8),
('no_wash_return', '🧽 Возврат без мойки', 'Можно вернуть автомобиль без обычной мойки. Сильное загрязнение оплачивается отдельно.', 20, 'fixed', null, 0, true, 9),
('cross_border', '🌍 Выезд за пределы Испании', 'Только по согласованию с менеджером', 0, 'request', null, 0, true, 10)
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  price_type = excluded.price_type,
  max_price = excluded.max_price,
  extra_km = excluded.extra_km,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

-- Правила аренды, пробег и согласие клиента.
alter table bookings add column if not exists included_km int;
alter table bookings add column if not exists included_km_per_day int default 200;
alter table bookings add column if not exists extra_km_price numeric(10,2) default 0.25;
alter table bookings add column if not exists rules_accepted boolean default false;
alter table bookings add column if not exists rules_accepted_at timestamptz;
alter table bookings add column if not exists rules_version text;

-- Предоплата для фиксации брони.
alter table bookings add column if not exists prepayment_amount numeric(10,2) default 0;
alter table bookings add column if not exists prepayment_status text default 'pending';
alter table bookings add column if not exists prepayment_paid_at timestamptz;
alter table bookings add column if not exists payment_method text;
alter table bookings add column if not exists remaining_amount numeric(10,2) default 0;

-- Новые статусы, которые используются в приложении:
-- pending_prepayment — заявка создана, ожидает предоплату
-- confirmed — предоплата отмечена админом, бронь подтверждена
-- cancelled — бронь отменена/отклонена

-- Stripe онлайн-оплата предоплаты.
alter table bookings add column if not exists online_payment_status text default 'not_started';
alter table bookings add column if not exists stripe_checkout_session_id text;
alter table bookings add column if not exists stripe_payment_intent_id text;
alter table bookings add column if not exists online_paid_amount numeric(10,2) default 0;
alter table bookings add column if not exists online_paid_at timestamptz;
alter table bookings add column if not exists payment_url text;
alter table bookings add column if not exists payment_type text default 'prepayment';

-- Новые статусы для онлайн-оплаты:
-- checkout_created — Stripe-ссылка создана
-- paid — предоплата успешно оплачена
-- paid_conflict — деньги получены, но даты требуют ручной проверки
-- payment_conflict — статус брони, если после оплаты обнаружилось пересечение дат

-- Ручная оплата / альтернативная предоплата.
alter table bookings add column if not exists manual_payment_requested_at timestamptz;
alter table bookings add column if not exists manual_payment_note text;

-- Документы водителя.
alter table bookings add column if not exists documents_status text default 'not_submitted';
alter table bookings add column if not exists documents_submitted_at timestamptz;
alter table bookings add column if not exists documents_reviewed_at timestamptz;
alter table bookings add column if not exists documents_phone text;
alter table bookings add column if not exists driver_license_path text;
alter table bookings add column if not exists identity_document_path text;

-- Private bucket for sensitive client documents.
insert into storage.buckets (id, name, public)
values ('booking-documents', 'booking-documents', false)
on conflict (id) do nothing;

-- Новые статусы:
-- pending_manual_payment — клиент не может оплатить онлайн, ожидает ручной способ оплаты
-- manual_requested — статус online_payment_status для ручного запроса
-- submitted / approved / rejected — статусы documents_status

-- Фотоосмотр, залог, штрафы, возврат авто и черный список.
alter table bookings add column if not exists pre_rental_photos_status text default 'not_uploaded';
alter table bookings add column if not exists pre_rental_photos_uploaded_at timestamptz;
alter table bookings add column if not exists post_rental_photos_status text default 'not_uploaded';
alter table bookings add column if not exists post_rental_photos_uploaded_at timestamptz;

alter table bookings add column if not exists deposit_status text default 'not_received';
alter table bookings add column if not exists deposit_received_at timestamptz;
alter table bookings add column if not exists deposit_returned_at timestamptz;
alter table bookings add column if not exists deposit_updated_at timestamptz;
alter table bookings add column if not exists deposit_held_amount numeric(10,2) default 0;
alter table bookings add column if not exists deposit_hold_reason text;

alter table bookings add column if not exists return_status text default 'not_returned';
alter table bookings add column if not exists return_checked_at timestamptz;
alter table bookings add column if not exists completed_at timestamptz;
alter table bookings add column if not exists has_pending_charges boolean default false;

create table if not exists booking_inspection_photos (
  id bigint generated by default as identity primary key,
  booking_id bigint references bookings(id) on delete cascade,
  stage text not null, -- before / after
  storage_path text not null,
  sort_order int default 0,
  created_at timestamptz default now()
);

create index if not exists booking_inspection_photos_booking_idx on booking_inspection_photos(booking_id);

create table if not exists booking_charges (
  id bigint generated by default as identity primary key,
  booking_id bigint references bookings(id) on delete cascade,
  category text not null, -- fine / toll / damage / cleaning / fuel / delay / deposit_hold
  amount numeric(10,2) not null default 0,
  admin_fee numeric(10,2) default 0,
  description text,
  status text default 'pending_payment',
  created_at timestamptz default now(),
  paid_at timestamptz
);

create index if not exists booking_charges_booking_idx on booking_charges(booking_id);

create table if not exists blocked_clients (
  id bigint generated by default as identity primary key,
  telegram_user_id text,
  telegram_username text,
  phone text,
  customer_name text,
  reason text,
  booking_id bigint unique references bookings(id) on delete set null,
  is_active boolean default true,
  created_at timestamptz default now()
);

create index if not exists blocked_clients_phone_idx on blocked_clients(phone);
create index if not exists blocked_clients_telegram_idx on blocked_clients(telegram_user_id);

-- Private bucket for before/after car inspection photos.
insert into storage.buckets (id, name, public)
values ('booking-inspections', 'booking-inspections', false)
on conflict (id) do nothing;

-- Новые значения статусов:
-- pre_rental_photos_status / post_rental_photos_status: not_uploaded / uploaded
-- deposit_status: not_received / received / returned / partially_held / held
-- return_status: not_returned / ok / dirty / fuel_missing / late / problem
-- booking_charges.status: pending_payment / paid / charged / cancelled
